# Generated by Django 4.2.13 on 2024-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch_code',
            field=models.CharField(default='001', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='branch_name',
            field=models.CharField(default='Main', max_length=50),
        ),
    ]
